apiVersion: apps/v1 # Version de l'api kubernetes
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: site-test
  template:
    metadata:
      labels:
        app: site-test
    spec:
      containers:
      - name: test-kube-deployment
        image: 127.0.0.1:5000/kubernetes_intro-app
        ports:
          - containerPort: 3000
        env:
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: test-configmap
                key: MYSQL_HOST
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef: # untilise une config map
                name: test-configmap
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:  # utilise un secret 
                name: test-secret
                key: MYSQL_PASSWORD
          - name: MYSQL_DB
            valueFrom:
              configMapKeyRef:
                name: test-configmap
                key: MYSQL_DB
